# Generated by Django 4.2.7 on 2023-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='trash',
        ),
        migrations.AddField(
            model_name='product',
            name='trash',
            field=models.ManyToManyField(to='backend.trashcomponent'),
        ),
    ]
